# Site settings
title: gitfetch
description: A neofetch-style CLI tool for GitHub, GitLab, Gitea, Forgejo, Codeberg, and Sourcehut statistics
url: "https://matars.github.io"
baseurl: "/gitfetch"

# Theme - using GitHub Pages supported theme
theme: jekyll-theme-primer

# Primer theme settings
show_downloads: true
github_username: Matars

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/Matars/gitfetch"

# Footer content
footer_content: 'Copyright &copy; 2025 Matars. Distributed by an <a href="https://github.com/Matars/gitfetch/blob/main/LICENSE">GPL-2.0</a> license.'
