name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-homebrew:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          repository: Matars/gitfetch
          path: gitfetch

      - name: Get version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep '^version =' gitfetch/pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Checkout tap repo
        uses: actions/checkout@v4
        with:
          repository: Matars/homebrew-gitfetch
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap

      - name: Update formula
        run: |
          chmod +x homebrew-tap/.github/scripts/update-homebrew.sh
          VERSION=${{ steps.get_version.outputs.version }} ./homebrew-tap/scripts/update-homebrew.sh

      - name: Commit and push
        run: |
          cd homebrew-tap
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/gitfetch.rb
          git commit -m "Update gitfetch to v${{ steps.get_version.outputs.version }}"
          git push
